- hosts: localhost
  # vars:
  #   name: tanay
  #   env: dev
  #   site: LA 
  #   alias:
  #     - shah
  #     - tsh
  tasks:
    - debug:
        msg: "{{ item }}"
      loop:
        - "{{ name }}"
        - "{{ env }}"
        - "{{ site }}"
        - "{{ alias }}"
    # - name: Test tasks
    #   ansible.builtin.debug:


