- hosts: localhost
  connection: local
  collections:
    - ansible.tower
  vars:
    # env: dev_123
    # os: rh
    # dev_123:
    #   rh: helllo
    # storage: '100'
    t_c: '4096'
    m_c: 16448
    ostype: Linux
  tasks:
    # - set_fact:
    #     num_list: "{{ num_list | debug([]) + [item | int ] }}"
    #   loop: "{{ storage.split(',') | list }}"
      #   list_alias: "{{ list_alias | default([]) + [vm+'.' + item] }}"
      # loop: "{{ alias }}"
    - set_fact:
        curr_hosts: "{{ groups[ostype] + [ new_host ] }}"
    

    - ansible.tower.tower_group:
        inventory: test
        name: "{{ ostype }}"
        state: present
        validate_certs: no
        hosts: "{{ curr_hosts }}"
    - debug:
        var: storage.split(',') | map('int') | list | sum
      
    # - fail:
    #   when: ((storage.split(',') | map('int') | list | sum) > max_storage) or (t_c | int > m_c)

      