---
# tasks file for multi_vault_test

- include_vars:
    name: "{{ item }}"
  loop:
    - "vars/sudo_pass.yml"
    - "vars/msg.yml"
    
- name: Debug Vaulted Creds
  debug:
    var: item
  loop:
    - "{{ awxsvc_pass }}"
    - "{{ msg }}"
